### ISSUE TITLE
Import button is disabled after data is imported

### ISSUE THREAD

**Issue by yelidrissi** [jigarius/toggl2redmine#28]
If you have 4 Toggl items ready for import. If you import 1 of them - on the subsequent screen, the imports will be grayed out for no reason, blocking further imports.

**Comment by jigarius** [comment]
Earlier, the plugin couldn't prevent users from re-importing the same entries, so this feature used to exist to prevent the user from doing repeated imports. Now that we have a way to disallow reimports, we can safely enable the "Import to Redmine" button after a round of imports have finished.
