### ISSUE TITLE
Disable time logging on closed projects

### ISSUE THREAD

**Issue by yelidrissi** [jigarius/toggl2redmine#31]
Toggl2Redmine can bypass permissions and log your time for a project where you are not an authorized user or manager. It can even log time in closed projects.

**Comment by jigarius** [comment]
This is similar to [issue 17](https://github.com/jigarius/toggl2redmine/issues/17). However, I will treat this as a request to disallow time logging on closed projects. Actually, I don't have any testing data locally, hence, I haven't been able to test a variety of cases.

**Comment by jigarius** [comment]
I closed a project on my local Redmine setup and tried to import time for it. I was shown an error message saying: _You are not allowed to log time on this project._

I get the same message when I try to log time against a project of which I'm not a member. I'll need some more information and a specific test case with which I can reproduce this error.
