### ISSUE TITLE
Possible Improvements

### ISSUE THREAD

**Issue by jigarius** [jigarius/toggl2redmine#41]
## Hide _duration rounding minutes_ if _Duration rounding_ is set to _Don't round_.

This displays the rounding minutes configuration only when it is relevant.

## Improve date formats

Currently we are at the mercy of JavaScript as far as date formats go. A better date format like _MMM DD, YYYY_ will be much better.

## Add a better confirmation message for _Import to Redmine_

Show the user exactly how many hours they have currently logged on Redmine and how many they will have logged after the import. Also, say that the process cannot be undone.

## Strikethrough tickets / projects which are closed

If a issue or project is marked as closed, then strike through the issue description to make it clear.

## Link _Projects_ to their respective pages

Currently, the user can click on issues, but they cannot click on projects! Maybe make the projects clickable as well?

**Comment by jigarius** [comment]
A delete button was added for Redmine time entries.

**Comment by piradata** [comment]
Hello Jigarius,

About the improvement 'Link Projects to their respective pages', in my PR one of the things I've add is a render link for the project of the issues, maybe that could help on this point.

**Comment by jigarius** [comment]
Closing this issue as issues have been created for most of these items.
