### ISSUE TITLE
Error: Could not fetch Toggl Workspaces. Please refresh the page to try again.

### ISSUE THREAD

**Issue by akawoj** [jigarius/toggl2redmine#42]
Hi,

thanks for great work!

I'm trying to use this plugin, but after providing API key I got: "Could not fetch Toggl Workspaces. Please refresh the page to try again." error on Toggl tab in Redmine. The timelog table below is empty. 
How can I fix this or find the reason of such behaviour?

**Comment by jigarius** [comment]
I have a theory, however, I need to know on what domain you are using the plugin.

**Comment by akawoj** [comment]
> I have a theory, however, I need to know on what domain you are using the plugin.
> […](#)

redmine._something_.pl

**Comment by jigarius** [comment]
I think you'll have to contact Toggl to whitelist your domain. I had to do it for my own setup as well. I'm trying to figure out a work around for this.

**Comment by akawoj** [comment]
What should I say to them? What do you mean by whitelist my domain? 
I was using toggl API for another plugin for redmine, from the same domain and it was working fine.

**Comment by jigarius** [comment]
Since some of the requests in my plugin are being made from client-side JS, Toggl needs to whitelist your domain. Just send them a link to my plugin and tell them that the requests are failing and that you want them to allow requests from your domain. Don't forget to send them the domain though :)

**Comment by akawoj** [comment]
thx, working on it

**Comment by akawoj** [comment]
My domain has been whitelisted and workspaces are loading properly. 

Now I got another problem - I can't see any hours from toggl - there is only endless loader on "Time logged on Toggl" section. I also have "Invalid Date" in "Last imported on" section.

**Comment by jigarius** [comment]
Can you tell me the version of Redmine you're using? Also, can you check the developer console to see if there are any JavaScript errors?

**Comment by jigarius** [comment]
BTW, just curious. Have you followed the [installation instructions](https://github.com/jigarius/toggl2redmine#installation) correctly? Especially the step where you run the migrations?

**Comment by akawoj** [comment]
We are using Redmine 3.4.9.stable

The errors from javascript console:

```
[Error] RangeError: Invalid Date
	toISOString (t2r.js:720)
	_getRawTogglTimeEntries (t2r.js:720)
	getTogglTimeEntries (t2r.js:765)
	updateTogglReport (t2r.js:842)
	(anonimowa funkcja) (t2r.js:413)
> T2RConsole.setVerboseMode(1)
< undefined
> T2RConsole.setVerboseMode()
< undefined
> T2RConsole.setVerboseMode
< function (status) {
  T2R.browserStorage('t2r.debug', status == true);
}
[Error] RangeError: Invalid Date
	toISOString (t2r.js:720)
	_getRawTogglTimeEntries (t2r.js:720)
	getTogglTimeEntries (t2r.js:765)
	updateTogglReport (t2r.js:842)
	(anonimowa funkcja) (t2r.js:413)

```

**Comment by akawoj** [comment]
And yes, we've done the migrations

**Comment by jigarius** [comment]
I think you're a victim of issue #43 as well. The migrations probably didn't run well. Try running the migrations again with the latest code on the `master` branch.

    RAILS_ENV=production bundle exec rake redmine:plugins:migrate

After this, try the plugin again. While you're on the plugin page, try doing a hard refresh and let me know how it goes.

If the problem persists, we can probably setup a screen sharing session so that I can see what's going and find the right fix.

**Comment by akawoj** [comment]
Hi,

I used the lastest code and did the migrations. No it works on macOS Chrome, still doesn't work on Safari (I did "hard refresh"). I will check it with other people on Safari and let you know.

**Comment by jigarius** [comment]
Aha! That might explain it. I've never tested it on Safari because it's a browser that not many people use. It's like Apple's Internet Explorer 😅 I'll do some tests on Safari.

**Comment by jigarius** [comment]
@akawoj I think it should work for you now. I tested it on Safari and found it to be working. There were three problems:

- There was an error in the way the date was being fetched from the URL fragment
- There was an error in the way the date filter was being stored and retrieved during execution
- There is a known cross browser compatibility issue with `Date.parse()`
  - I've replace `Date.parse()` with `new Date(y, m, d, h, i, s, ms)`

The **fixes are in the 3.x branch**. Let me know if you can use the plugin now.

**Comment by akawoj** [comment]
I've installed the latest version, did the hard refresh and still no luck on Safari ("invalid date" errors in javascript console)

**Comment by jigarius** [comment]
That is highly strange. So, you did:
* Get the latest code for toggl2redmine
* Replace the old code with the new one
* Restart Remine
* Make sure all the migrations were executed properly
* Try the plugin in Safari after a hard refresh (if needed)

If the above steps don't work for you, would you be able to do a screen-sharing session so that I can help you further?

As for me, it now works correctly on Safari as well as Chrome.

**Comment by akawoj** [comment]
It work, I had to manually clean Safari cache. Thanks for your help and very good work with plugin.
