### ISSUE TITLE
Migration error: uninitialized constant CreateTogglTimeEntriesTable

### ISSUE THREAD

**Issue by mepoohsta** [jigarius/toggl2redmine#43]
Migrating toggl2redmine (Toggl 2 Redmine)...
rake aborted!
NameError: uninitialized constant CreateTogglTimeEntriesTable

**Comment by jigarius** [comment]
Which version of Remine do you have? The plugin only works with specific versions of Remine.

**Comment by mepoohsta** [comment]
Environment:
  Redmine version                3.4.9.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2

@jigarius

**Comment by jigarius** [comment]
Try the code in the latest `master` branch and let me know if that fixes the problem.

**Comment by jigarius** [comment]
@mepoohsta I just tested this on my Redmine install and the commit that I've made above has actually fixed the problem. The file name did not match the class name, so Rails could not load the class. After renaming the file, the autoloader finds the class correctly, thereby eliminating the error.
