### ISSUE TITLE
Bulk import by date range

### ISSUE THREAD

**Issue by akawoj** [jigarius/toggl2redmine#45]
Are there any plans for bulk import support? I would like to have possibility to import one month or 2 weeks in one batch.

**Comment by jigarius** [comment]
There are some people who suggested that, however, I have no hard plans for this feature as such. The intended use case is import if time everyday, hence the absence of data ranges.

**Comment by jigarius** [comment]
It sees not many users use this plugin, so I think this feature won't be worked on any time soon.
