### ISSUE TITLE
Disabling alert messages prevents creation of time entries

### ISSUE THREAD

**Issue by piradata** [jigarius/toggl2redmine#58]
## Steps to reproduce

* Delete a time entry
  * When a confirmation alert message appears, choose to block alert messages.
* Now, proceed to *import to Redmine*
* Notice that import won't work because alert messages have been disabled.

**Comment by jigarius** [comment]
This seems like it works as designed. The alert message for deleting time entries comes from Redmine. Also, it is good to confirm before deletion. I think the problem can be resolved by not blocking the alert message? I think the latest version of Toggl2Redmine allows you to select multiple time entries and delete them all at once, so you won't need to deal with multiple alert messages - simply confirm deletion once. Does that solve the problem?

**Comment by jigarius** [comment]
I think this works as designed. Many apps rely on the browser's `confirm` and `alert` functions.
