### ISSUE TITLE
Toggl API domain change

### ISSUE THREAD

**Issue by kporras07** [jigarius/toggl2redmine#60]
Hi @jigarius,

Toggl recently announced that they'll be removing www.toggl.com domain for API. It should be changed to api.track.toggl.com. 

```
Hi there,

We are reaching out because we detected API usage coming from your Toggl Track account using the www.toggl.com(or toggl.com) domain.

After last year's rebranding, we released api.track.toggl.com as our new domain for API usage. These changes were communicated via newsletter and the following blog post. The API Docs were also updated to reflect the domain changes.

We want to inform you that the usage of www.toggl.com(or toggl.com) domain for the API will be dropped after 'June 30th 2021'.

We encourage you to perform the switch to api.track.toggl.com as soon as possible in order to prevent disruption.

Best wishes,
The Toggl Track Team
support@track.toggl.com
```

Do you have this change already in a roadmap or will you be interested in a PR to do this change?

Thanks,

**Comment by jigarius** [comment]
Thanks for letting me know. I'll try to work on it this weekend. If you have time, it'll be great if you could create a PR.

Most Toggl requests are made from the `TogglService` if I remember correctly, which should probably have a constant defining the API URL.

**Comment by jigarius** [comment]
@kporras07 I've added a commit for this to the `4.x-dev` branch. Once you confirm that it's working well, I'll tag a new release which you can install on your Redmine.

**Comment by kporras07** [comment]
@jigarius I just tested this and it works as expected. Thanks
